name: Sync labels
on:
  push:
    branches:
      - dev
    paths:
    - .github/labels.yaml
  workflow_dispatch: # Allow manual syncs
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: micnncim/action-label-syncer@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/labels.yaml
